[api]
enabled = true  # true | false
bind = ":9290"  # bind host:port

[servers.fwsu]
 bind = "0.0.0.0:9090"
 protocol = "udp"
 balance = "roundrobin"
 backend_idle_timeout="0"
 client_idle_timeout="0"

[servers.fwsu.udp]
 max_requests = 1
 max_responses = 0

[servers.fwsu.discovery]
 kind = "static"
 static_list = [
  "as-logstash-00:9090",
  "as-logstash-01:9090"
 ]

[servers.fwsu.healthcheck]
 interval = "30s"
 kind = "exec"
 exec_command = "./hc.sh"
 exec_expected_positive_output = "1"
 exec_expected_negative_output = "0"
 timeout = "5s"


[servers.solutions]
 bind = "0.0.0.0:9106"
 protocol = "udp"
 balance = "roundrobin"
 backend_idle_timeout="0"
 client_idle_timeout="0"
 max_responses = 0

[servers.solutions.udp]
 max_requests = 1
 max_responses = 0

[servers.solutions.discovery]
 kind = "static"
 static_list = [
  "as-logstash-00:9106",
  "as-logstash-01:9106"
 ]

[servers.solutions.healthcheck]
 interval = "30s"
 kind = "exec"
 exec_command = "./hc.sh"
 exec_expected_positive_output = "1"
 exec_expected_negative_output = "0"
 timeout = "5s"
